### ISSUE TITLE
`small::multimap::erase(Key)` does not erase all matching elements

### ISSUE THREAD

**Issue by tearfur** [alandefreitas/small#35]
## The problem

As the title suggests, `small::multimap::erase(Key)` only erases 1 element, instead of all elements with the same key.

### Steps to Reproduce

<details>
<summary>CMakeLists.txt</summary>

```cmake
cmake_minimum_required(VERSION 3.22)
project(small_test)

set(CMAKE_CXX_STANDARD 17)

add_subdirectory(small)
add_executable(small_test main.cpp)
target_link_libraries(small_test PUBLIC small::small)
```

</details>

```c++
#include <iostream>

#include <small/map.hpp>

int main() {
    small::multimap<int, int> a = {{1, 1}, {1, 1}, {2, 2}, {3, 3}};

    std::cout << "Number of items erased: " << a.erase(1) << '\n';
    for (auto const& [key, val] : a)
        std::cout << "key: " << key << ", val: " << val << '\n';

    return 0;
}
```

### Output

<details>
 
```console
Number of items erased: 1
key: 1, val: 1
key: 2, val: 2
key: 3, val: 3
```
</details>

## Platform

- [x] *cross-platform issue - linux*
- [ ] *cross-platform issue - windows*
- [ ] *cross-platform issue - macos*
- [ ] *other:* ___________

### Environment Details
 - OS: Ubuntu
 - OS Version: 22.04
 - Compiler: g++
 - Compiler version: Ubuntu 11.4.0-1ubuntu1~22.04

**Comment by tearfur** [comment]
Hi @alandefreitas, really great library you've written here. It has been very useful for the Transmission project.
We have used `small::vector` extensively, and we found ourselves wanting to use your flat maps as well.

It looks like the `associative_vector` code still needs some work before it is production ready, may I know if you have any plans of continuing work on this project?

**Comment by alandefreitas** [comment]
> As the title suggests, small::multimap::erase(Key) only erases 1 element, instead of all elements with the same key.

True. I failed to notice that was the behavior of `std::multimap::erase` and match it.

> Hi @alandefreitas, really great library you've written here. It has been very useful for the Transmission project.

Thanks. I'm happy it helped.

> It looks like the associative_vector code still needs some work before it is production ready, may I know if you have any plans of continuing work on this project?

You're correct. I haven't had much time outside my daytime job to invest in this project. I would love to invest more in tests and CI but I can't. Even at the time of writing this library, most attention went to the vector and string implementations.

I believe `small::vector` is the most useful container in the library because `boost::small_vector` is way too much if you have access to C++17. With `constexpr if`, I have even simpler versions of static vectors I wrote as implementation details in other libraries.

For flat maps and maps in general, things have changed quite a lot since I wrote this library. You're unlikely to find anything better than the [new containers in Boost.Unordered](https://www.boost.org/doc/libs/1_83_0/libs/unordered/doc/html/unordered.html).

They're not static though. If you need a static flat map (implying there are few elements), in most cases just using a `small::vector<std::pair<K, V>>` is the best you can get. If you don't need it to be static, it's going to be hard to beat `boost::unordered_flat_map`.

**Comment by tearfur** [comment]
I'm afraid our maintainers aren't very fond of the idea of using Boost though, and I understand that, especially we don't need a lot of it, so bloating our executable size and build times might not be worth it.

Our use case is that we have a map that we frequently modify and access, both sequentially and randomly. I thought your flat maps are perfect for this, since it saves me the trouble of writing code to lookup a vector and maintaining sort order when inserting.

**Comment by alandefreitas** [comment]
> I'm afraid our maintainers aren't very fond of the idea of using Boost

Yes. I thought that could be the case. It's possible to download only the parts of boost you need with boostdep but it's still an inconvenience to replicate. Executable size and build times should not be impacted as long as you're not instantiating other classes.

> Our use case is that we have a map that we frequently modify and access, both sequentially and randomly. 

Mmm... If this map can grow arbitrarily, this flat map won't work that well, so I guess you need a regular `std::unordered_map`, even if the implementation is not as good as `boost::unordered_flat_map`.

If the number of elements has an upper bound, then the map in this library can be useful, but you might find issues on the way because it's not as well-tested as other containers.

**Comment by tearfur** [comment]
> If the number of elements has an upper bound, then the map in this library can be useful

Yes, that's exactly our case.

> but you might find issues on the way because it's not as well-tested as other containers.

I'm already finding a lot of them, prepare for an PR onslaught. 😆

**Comment by alandefreitas** [comment]
> I'm already finding a lot of them, prepare for an PR onslaught. 😆

😆 

Yes. These maps aren't as good as they could be but it's still salvageable.
